# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import thingsboard_client
from thingsboard_client.rest import ApiException
from thingsboard_client.apis.usercontroller_api import UsercontrollerApi


class TestUsercontrollerApi(unittest.TestCase):
    """ UsercontrollerApi unit test stubs """

    def setUp(self):
        self.api = thingsboard_client.apis.usercontroller_api.UsercontrollerApi()

    def tearDown(self):
        pass

    def test_delete_user_using_delete(self):
        """
        Test case for delete_user_using_delete

        deleteUser
        """
        pass

    def test_get_activation_link_using_get(self):
        """
        Test case for get_activation_link_using_get

        getActivationLink
        """
        pass

    def test_get_customer_users_using_get(self):
        """
        Test case for get_customer_users_using_get

        getCustomerUsers
        """
        pass

    def test_get_tenant_admins_using_get(self):
        """
        Test case for get_tenant_admins_using_get

        getTenantAdmins
        """
        pass

    def test_get_user_by_id_using_get(self):
        """
        Test case for get_user_by_id_using_get

        getUserById
        """
        pass

    def test_get_user_token_using_get(self):
        """
        Test case for get_user_token_using_get

        getUserToken
        """
        pass

    def test_is_user_token_access_enabled_using_get(self):
        """
        Test case for is_user_token_access_enabled_using_get

        isUserTokenAccessEnabled
        """
        pass

    def test_save_user_using_post(self):
        """
        Test case for save_user_using_post

        saveUser
        """
        pass

    def test_send_activation_email_using_post(self):
        """
        Test case for send_activation_email_using_post

        sendActivationEmail
        """
        pass


if __name__ == '__main__':
    unittest.main()
