# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import thingsboard_client
from thingsboard_client.rest import ApiException
from thingsboard_client.apis.devicecontroller_api import DevicecontrollerApi


class TestDevicecontrollerApi(unittest.TestCase):
    """ DevicecontrollerApi unit test stubs """

    def setUp(self):
        self.api = thingsboard_client.apis.devicecontroller_api.DevicecontrollerApi()

    def tearDown(self):
        pass

    def test_assign_device_to_customer_using_post(self):
        """
        Test case for assign_device_to_customer_using_post

        assignDeviceToCustomer
        """
        pass

    def test_assign_device_to_public_customer_using_post(self):
        """
        Test case for assign_device_to_public_customer_using_post

        assignDeviceToPublicCustomer
        """
        pass

    def test_delete_device_using_delete(self):
        """
        Test case for delete_device_using_delete

        deleteDevice
        """
        pass

    def test_find_by_query_using_post1(self):
        """
        Test case for find_by_query_using_post1

        findByQuery
        """
        pass

    def test_get_customer_devices_using_get(self):
        """
        Test case for get_customer_devices_using_get

        getCustomerDevices
        """
        pass

    def test_get_device_by_id_using_get(self):
        """
        Test case for get_device_by_id_using_get

        getDeviceById
        """
        pass

    def test_get_device_credentials_by_device_id_using_get(self):
        """
        Test case for get_device_credentials_by_device_id_using_get

        getDeviceCredentialsByDeviceId
        """
        pass

    def test_get_device_types_using_get(self):
        """
        Test case for get_device_types_using_get

        getDeviceTypes
        """
        pass

    def test_get_devices_by_ids_using_get(self):
        """
        Test case for get_devices_by_ids_using_get

        getDevicesByIds
        """
        pass

    def test_get_tenant_device_using_get(self):
        """
        Test case for get_tenant_device_using_get

        getTenantDevice
        """
        pass

    def test_save_device_credentials_using_post(self):
        """
        Test case for save_device_credentials_using_post

        saveDeviceCredentials
        """
        pass

    def test_save_device_using_post(self):
        """
        Test case for save_device_using_post

        saveDevice
        """
        pass

    def test_unassign_device_from_customer_using_delete(self):
        """
        Test case for unassign_device_from_customer_using_delete

        unassignDeviceFromCustomer
        """
        pass


if __name__ == '__main__':
    unittest.main()
