# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import thingsboard_client
from thingsboard_client.rest import ApiException
from thingsboard_client.apis.dashboardcontroller_api import DashboardcontrollerApi


class TestDashboardcontrollerApi(unittest.TestCase):
    """ DashboardcontrollerApi unit test stubs """

    def setUp(self):
        self.api = thingsboard_client.apis.dashboardcontroller_api.DashboardcontrollerApi()

    def tearDown(self):
        pass

    def test_add_dashboard_customers_using_post(self):
        """
        Test case for add_dashboard_customers_using_post

        addDashboardCustomers
        """
        pass

    def test_assign_dashboard_to_customer_using_post(self):
        """
        Test case for assign_dashboard_to_customer_using_post

        assignDashboardToCustomer
        """
        pass

    def test_assign_dashboard_to_public_customer_using_post(self):
        """
        Test case for assign_dashboard_to_public_customer_using_post

        assignDashboardToPublicCustomer
        """
        pass

    def test_delete_dashboard_using_delete(self):
        """
        Test case for delete_dashboard_using_delete

        deleteDashboard
        """
        pass

    def test_get_customer_dashboards_using_get(self):
        """
        Test case for get_customer_dashboards_using_get

        getCustomerDashboards
        """
        pass

    def test_get_dashboard_by_id_using_get(self):
        """
        Test case for get_dashboard_by_id_using_get

        getDashboardById
        """
        pass

    def test_get_dashboard_info_by_id_using_get(self):
        """
        Test case for get_dashboard_info_by_id_using_get

        getDashboardInfoById
        """
        pass

    def test_get_server_time_using_get(self):
        """
        Test case for get_server_time_using_get

        getServerTime
        """
        pass

    def test_get_tenant_dashboards_using_get(self):
        """
        Test case for get_tenant_dashboards_using_get

        getTenantDashboards
        """
        pass

    def test_get_tenant_dashboards_using_get1(self):
        """
        Test case for get_tenant_dashboards_using_get1

        getTenantDashboards
        """
        pass

    def test_remove_dashboard_customers_using_post(self):
        """
        Test case for remove_dashboard_customers_using_post

        removeDashboardCustomers
        """
        pass

    def test_save_dashboard_using_post(self):
        """
        Test case for save_dashboard_using_post

        saveDashboard
        """
        pass

    def test_unassign_dashboard_from_customer_using_delete(self):
        """
        Test case for unassign_dashboard_from_customer_using_delete

        unassignDashboardFromCustomer
        """
        pass

    def test_unassign_dashboard_from_public_customer_using_delete(self):
        """
        Test case for unassign_dashboard_from_public_customer_using_delete

        unassignDashboardFromPublicCustomer
        """
        pass

    def test_update_dashboard_customers_using_post(self):
        """
        Test case for update_dashboard_customers_using_post

        updateDashboardCustomers
        """
        pass


if __name__ == '__main__':
    unittest.main()
