# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import thingsboard_client
from thingsboard_client.rest import ApiException
from thingsboard_client.apis.telemetrycontroller_api import TelemetrycontrollerApi


class TestTelemetrycontrollerApi(unittest.TestCase):
    """ TelemetrycontrollerApi unit test stubs """

    def setUp(self):
        self.api = thingsboard_client.apis.telemetrycontroller_api.TelemetrycontrollerApi()

    def tearDown(self):
        pass

    def test_delete_entity_attributes_using_delete(self):
        """
        Test case for delete_entity_attributes_using_delete

        deleteEntityAttributes
        """
        pass

    def test_delete_entity_attributes_using_delete1(self):
        """
        Test case for delete_entity_attributes_using_delete1

        deleteEntityAttributes
        """
        pass

    def test_get_attribute_keys_by_scope_using_get(self):
        """
        Test case for get_attribute_keys_by_scope_using_get

        getAttributeKeysByScope
        """
        pass

    def test_get_attribute_keys_using_get(self):
        """
        Test case for get_attribute_keys_using_get

        getAttributeKeys
        """
        pass

    def test_get_attributes_by_scope_using_get(self):
        """
        Test case for get_attributes_by_scope_using_get

        getAttributesByScope
        """
        pass

    def test_get_attributes_using_get(self):
        """
        Test case for get_attributes_using_get

        getAttributes
        """
        pass

    def test_get_latest_timeseries_using_get(self):
        """
        Test case for get_latest_timeseries_using_get

        getLatestTimeseries
        """
        pass

    def test_get_timeseries_keys_using_get(self):
        """
        Test case for get_timeseries_keys_using_get

        getTimeseriesKeys
        """
        pass

    def test_save_device_attributes_using_post(self):
        """
        Test case for save_device_attributes_using_post

        saveDeviceAttributes
        """
        pass

    def test_save_entity_attributes_v1_using_post(self):
        """
        Test case for save_entity_attributes_v1_using_post

        saveEntityAttributesV1
        """
        pass

    def test_save_entity_attributes_v2_using_post(self):
        """
        Test case for save_entity_attributes_v2_using_post

        saveEntityAttributesV2
        """
        pass

    def test_save_entity_telemetry_using_post(self):
        """
        Test case for save_entity_telemetry_using_post

        saveEntityTelemetry
        """
        pass

    def test_save_entity_telemetry_with_ttl_using_post(self):
        """
        Test case for save_entity_telemetry_with_ttl_using_post

        saveEntityTelemetryWithTTL
        """
        pass


if __name__ == '__main__':
    unittest.main()
