# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import thingsboard_client
from thingsboard_client.rest import ApiException
from thingsboard_client.apis.assetcontroller_api import AssetcontrollerApi


class TestAssetcontrollerApi(unittest.TestCase):
    """ AssetcontrollerApi unit test stubs """

    def setUp(self):
        self.api = thingsboard_client.apis.assetcontroller_api.AssetcontrollerApi()

    def tearDown(self):
        pass

    def test_assign_asset_to_customer_using_post(self):
        """
        Test case for assign_asset_to_customer_using_post

        assignAssetToCustomer
        """
        pass

    def test_assign_asset_to_public_customer_using_post(self):
        """
        Test case for assign_asset_to_public_customer_using_post

        assignAssetToPublicCustomer
        """
        pass

    def test_delete_asset_using_delete(self):
        """
        Test case for delete_asset_using_delete

        deleteAsset
        """
        pass

    def test_find_by_query_using_post(self):
        """
        Test case for find_by_query_using_post

        findByQuery
        """
        pass

    def test_get_asset_by_id_using_get(self):
        """
        Test case for get_asset_by_id_using_get

        getAssetById
        """
        pass

    def test_get_asset_types_using_get(self):
        """
        Test case for get_asset_types_using_get

        getAssetTypes
        """
        pass

    def test_get_assets_by_ids_using_get(self):
        """
        Test case for get_assets_by_ids_using_get

        getAssetsByIds
        """
        pass

    def test_get_customer_assets_using_get(self):
        """
        Test case for get_customer_assets_using_get

        getCustomerAssets
        """
        pass

    def test_get_tenant_asset_using_get(self):
        """
        Test case for get_tenant_asset_using_get

        getTenantAsset
        """
        pass

    def test_save_asset_using_post(self):
        """
        Test case for save_asset_using_post

        saveAsset
        """
        pass

    def test_unassign_asset_from_customer_using_delete(self):
        """
        Test case for unassign_asset_from_customer_using_delete

        unassignAssetFromCustomer
        """
        pass


if __name__ == '__main__':
    unittest.main()
