# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import thingsboard_client
from thingsboard_client.rest import ApiException
from thingsboard_client.apis.rpccontroller_api import RpccontrollerApi


class TestRpccontrollerApi(unittest.TestCase):
    """ RpccontrollerApi unit test stubs """

    def setUp(self):
        self.api = thingsboard_client.apis.rpccontroller_api.RpccontrollerApi()

    def tearDown(self):
        pass

    def test_handle_one_way_device_rpc_request_using_post(self):
        """
        Test case for handle_one_way_device_rpc_request_using_post

        handleOneWayDeviceRPCRequest
        """
        pass

    def test_handle_two_way_device_rpc_request_using_post(self):
        """
        Test case for handle_two_way_device_rpc_request_using_post

        handleTwoWayDeviceRPCRequest
        """
        pass


if __name__ == '__main__':
    unittest.main()
