# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class DashboardInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, assigned_customers=None, created_time=None, id=None, name=None, tenant_id=None, title=None):
        """
        DashboardInfo - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'assigned_customers': 'list[ShortCustomerInfo]',
            'created_time': 'int',
            'id': 'DashboardId',
            'name': 'str',
            'tenant_id': 'TenantId',
            'title': 'str'
        }

        self.attribute_map = {
            'assigned_customers': 'assignedCustomers',
            'created_time': 'createdTime',
            'id': 'id',
            'name': 'name',
            'tenant_id': 'tenantId',
            'title': 'title'
        }

        self._assigned_customers = assigned_customers
        self._created_time = created_time
        self._id = id
        self._name = name
        self._tenant_id = tenant_id
        self._title = title

    @property
    def assigned_customers(self):
        """
        Gets the assigned_customers of this DashboardInfo.


        :return: The assigned_customers of this DashboardInfo.
        :rtype: list[ShortCustomerInfo]
        """
        return self._assigned_customers

    @assigned_customers.setter
    def assigned_customers(self, assigned_customers):
        """
        Sets the assigned_customers of this DashboardInfo.


        :param assigned_customers: The assigned_customers of this DashboardInfo.
        :type: list[ShortCustomerInfo]
        """

        self._assigned_customers = assigned_customers

    @property
    def created_time(self):
        """
        Gets the created_time of this DashboardInfo.


        :return: The created_time of this DashboardInfo.
        :rtype: int
        """
        return self._created_time

    @created_time.setter
    def created_time(self, created_time):
        """
        Sets the created_time of this DashboardInfo.


        :param created_time: The created_time of this DashboardInfo.
        :type: int
        """

        self._created_time = created_time

    @property
    def id(self):
        """
        Gets the id of this DashboardInfo.


        :return: The id of this DashboardInfo.
        :rtype: DashboardId
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this DashboardInfo.


        :param id: The id of this DashboardInfo.
        :type: DashboardId
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this DashboardInfo.


        :return: The name of this DashboardInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this DashboardInfo.


        :param name: The name of this DashboardInfo.
        :type: str
        """

        self._name = name

    @property
    def tenant_id(self):
        """
        Gets the tenant_id of this DashboardInfo.


        :return: The tenant_id of this DashboardInfo.
        :rtype: TenantId
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """
        Sets the tenant_id of this DashboardInfo.


        :param tenant_id: The tenant_id of this DashboardInfo.
        :type: TenantId
        """

        self._tenant_id = tenant_id

    @property
    def title(self):
        """
        Gets the title of this DashboardInfo.


        :return: The title of this DashboardInfo.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """
        Sets the title of this DashboardInfo.


        :param title: The title of this DashboardInfo.
        :type: str
        """

        self._title = title

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
