# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class Device(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, additional_info=None, created_time=None, customer_id=None, id=None, name=None, tenant_id=None, type=None):
        """
        Device - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'additional_info': 'str',
            'created_time': 'int',
            'customer_id': 'CustomerId',
            'id': 'DeviceId',
            'name': 'str',
            'tenant_id': 'TenantId',
            'type': 'str'
        }

        self.attribute_map = {
            'additional_info': 'additionalInfo',
            'created_time': 'createdTime',
            'customer_id': 'customerId',
            'id': 'id',
            'name': 'name',
            'tenant_id': 'tenantId',
            'type': 'type'
        }

        self._additional_info = additional_info
        self._created_time = created_time
        self._customer_id = customer_id
        self._id = id
        self._name = name
        self._tenant_id = tenant_id
        self._type = type

    @property
    def additional_info(self):
        """
        Gets the additional_info of this Device.


        :return: The additional_info of this Device.
        :rtype: str
        """
        return self._additional_info

    @additional_info.setter
    def additional_info(self, additional_info):
        """
        Sets the additional_info of this Device.


        :param additional_info: The additional_info of this Device.
        :type: str
        """

        self._additional_info = additional_info

    @property
    def created_time(self):
        """
        Gets the created_time of this Device.


        :return: The created_time of this Device.
        :rtype: int
        """
        return self._created_time

    @created_time.setter
    def created_time(self, created_time):
        """
        Sets the created_time of this Device.


        :param created_time: The created_time of this Device.
        :type: int
        """

        self._created_time = created_time

    @property
    def customer_id(self):
        """
        Gets the customer_id of this Device.


        :return: The customer_id of this Device.
        :rtype: CustomerId
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id):
        """
        Sets the customer_id of this Device.


        :param customer_id: The customer_id of this Device.
        :type: CustomerId
        """

        self._customer_id = customer_id

    @property
    def id(self):
        """
        Gets the id of this Device.


        :return: The id of this Device.
        :rtype: DeviceId
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Device.


        :param id: The id of this Device.
        :type: DeviceId
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this Device.


        :return: The name of this Device.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Device.


        :param name: The name of this Device.
        :type: str
        """

        self._name = name

    @property
    def tenant_id(self):
        """
        Gets the tenant_id of this Device.


        :return: The tenant_id of this Device.
        :rtype: TenantId
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """
        Sets the tenant_id of this Device.


        :param tenant_id: The tenant_id of this Device.
        :type: TenantId
        """

        self._tenant_id = tenant_id

    @property
    def type(self):
        """
        Gets the type of this Device.


        :return: The type of this Device.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Device.


        :param type: The type of this Device.
        :type: str
        """

        self._type = type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
