# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class ShortCustomerInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, customer_id=None, public=None, title=None, is_public=None):
        """
        ShortCustomerInfo - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'customer_id': 'CustomerId',
            'public': 'bool',
            'title': 'str',
            'is_public': 'bool'
        }

        self.attribute_map = {
            'customer_id': 'customerId',
            'public': 'public',
            'title': 'title',
            'is_public': 'isPublic'
        }

        self._customer_id = customer_id
        self._public = public
        self._title = title
        self._is_public = is_public

    @property
    def customer_id(self):
        """
        Gets the customer_id of this ShortCustomerInfo.


        :return: The customer_id of this ShortCustomerInfo.
        :rtype: CustomerId
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id):
        """
        Sets the customer_id of this ShortCustomerInfo.


        :param customer_id: The customer_id of this ShortCustomerInfo.
        :type: CustomerId
        """

        self._customer_id = customer_id

    @property
    def public(self):
        """
        Gets the public of this ShortCustomerInfo.


        :return: The public of this ShortCustomerInfo.
        :rtype: bool
        """
        return self._public

    @public.setter
    def public(self, public):
        """
        Sets the public of this ShortCustomerInfo.


        :param public: The public of this ShortCustomerInfo.
        :type: bool
        """

        self._public = public

    @property
    def title(self):
        """
        Gets the title of this ShortCustomerInfo.


        :return: The title of this ShortCustomerInfo.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """
        Sets the title of this ShortCustomerInfo.


        :param title: The title of this ShortCustomerInfo.
        :type: str
        """

        self._title = title

    @property
    def is_public(self):
        """
        Gets the is_public of this ShortCustomerInfo.


        :return: The is_public of this ShortCustomerInfo.
        :rtype: bool
        """
        return self._is_public

    @is_public.setter
    def is_public(self, is_public):
        """
        Sets the is_public of this ShortCustomerInfo.


        :param is_public: The is_public of this ShortCustomerInfo.
        :type: bool
        """

        self._is_public = is_public

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
