# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into sdk package
from .models.admin_settings import AdminSettings
from .models.admin_settings_id import AdminSettingsId
from .models.alarm import Alarm
from .models.alarm_id import AlarmId
from .models.alarm_info import AlarmInfo
from .models.asset import Asset
from .models.asset_id import AssetId
from .models.asset_search_query import AssetSearchQuery
from .models.audit_log import AuditLog
from .models.audit_log_id import AuditLogId
from .models.billing_info_response import BillingInfoResponse
from .models.component_descriptor import ComponentDescriptor
from .models.component_descriptor_id import ComponentDescriptorId
from .models.customer import Customer
from .models.customer_id import CustomerId
from .models.dashboard import Dashboard
from .models.dashboard_id import DashboardId
from .models.dashboard_info import DashboardInfo
from .models.deferred_result_response_entity import DeferredResultResponseEntity
from .models.device import Device
from .models.device_credentials import DeviceCredentials
from .models.device_credentials_id import DeviceCredentialsId
from .models.device_id import DeviceId
from .models.device_search_query import DeviceSearchQuery
from .models.entity_id import EntityId
from .models.entity_relation import EntityRelation
from .models.entity_relation_info import EntityRelationInfo
from .models.entity_relations_query import EntityRelationsQuery
from .models.entity_subtype import EntitySubtype
from .models.entity_type_filter import EntityTypeFilter
from .models.event import Event
from .models.event_id import EventId
from .models.node_connection_info import NodeConnectionInfo
from .models.relations_search_parameters import RelationsSearchParameters
from .models.response_entity import ResponseEntity
from .models.rule_chain import RuleChain
from .models.rule_chain_connection_info import RuleChainConnectionInfo
from .models.rule_chain_id import RuleChainId
from .models.rule_chain_meta_data import RuleChainMetaData
from .models.rule_node import RuleNode
from .models.rule_node_id import RuleNodeId
from .models.short_customer_info import ShortCustomerInfo
from .models.tenant import Tenant
from .models.tenant_id import TenantId
from .models.text_page_data_asset import TextPageDataAsset
from .models.text_page_data_customer import TextPageDataCustomer
from .models.text_page_data_dashboard_info import TextPageDataDashboardInfo
from .models.text_page_data_device import TextPageDataDevice
from .models.text_page_data_rule_chain import TextPageDataRuleChain
from .models.text_page_data_tenant import TextPageDataTenant
from .models.text_page_data_user import TextPageDataUser
from .models.text_page_data_widgets_bundle import TextPageDataWidgetsBundle
from .models.text_page_link import TextPageLink
from .models.time_page_data_alarm_info import TimePageDataAlarmInfo
from .models.time_page_data_audit_log import TimePageDataAuditLog
from .models.time_page_data_dashboard_info import TimePageDataDashboardInfo
from .models.time_page_data_event import TimePageDataEvent
from .models.time_page_link import TimePageLink
from .models.update_message import UpdateMessage
from .models.user import User
from .models.user_id import UserId
from .models.widget_type import WidgetType
from .models.widget_type_id import WidgetTypeId
from .models.widgets_bundle import WidgetsBundle
from .models.widgets_bundle_id import WidgetsBundleId

# import apis into sdk package
from .apis.admincontroller_api import AdmincontrollerApi
from .apis.alarmcontroller_api import AlarmcontrollerApi
from .apis.assetcontroller_api import AssetcontrollerApi
from .apis.auditlogcontroller_api import AuditlogcontrollerApi
from .apis.authcontroller_api import AuthcontrollerApi
from .apis.billingcontroller_api import BillingcontrollerApi
from .apis.componentdescriptorcontroller_api import ComponentdescriptorcontrollerApi
from .apis.customercontroller_api import CustomercontrollerApi
from .apis.dashboardcontroller_api import DashboardcontrollerApi
from .apis.deviceapicontroller_api import DeviceapicontrollerApi
from .apis.devicecontroller_api import DevicecontrollerApi
from .apis.entityrelationcontroller_api import EntityrelationcontrollerApi
from .apis.eventcontroller_api import EventcontrollerApi
from .apis.rpccontroller_api import RpccontrollerApi
from .apis.rulechaincontroller_api import RulechaincontrollerApi
from .apis.telemetrycontroller_api import TelemetrycontrollerApi
from .apis.tenantcontroller_api import TenantcontrollerApi
from .apis.usercontroller_api import UsercontrollerApi
from .apis.widgetsbundlecontroller_api import WidgetsbundlecontrollerApi
from .apis.widgettypecontroller_api import WidgettypecontrollerApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
